repos:
-   repo: local
    hooks:
      - id: lint
        name: lint
        entry: poetry run make lint
        language: system
        types: [python]
#
#      - id: tests
#        name: tests_run
#        entry: poetry run make test
#        language: system
#        types: [ python ]
